# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_img',
            name='banner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='banner_img',
            table='banner_img',
        ),
    ]
