# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190706_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.IntegerField()),
                ('floor_title', models.CharField(max_length=20)),
                ('floor_banner_id', models.IntegerField()),
                ('floor_img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('floor', models.ManyToManyField(to='App.Floor')),
            ],
        ),
    ]
