# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190707_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'floor_goods',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='floor',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
