# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20190712_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('package', models.CharField(max_length=50)),
                ('small_img', models.CharField(max_length=50)),
                ('middle_img', models.CharField(max_length=50)),
                ('big_img', models.CharField(max_length=50)),
            ],
        ),
    ]
