# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20190716_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price2',
            field=models.FloatField(default=1280),
            preserve_default=False,
        ),
    ]
