# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20190718_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='all_price',
            field=models.FloatField(default=0),
        ),
    ]
