# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_cart_is_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Cart'),
        ),
    ]
