# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-20 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20190720_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_pied',
            field=models.BooleanField(default=0),
        ),
    ]
